### ISSUE TITLE
Email is not saved correctly on my profile

### ISSUE THREAD

**Issue by joaoaguiam** [uport-project/3box-dapp#110]
**Describe the bug**
When I update my email on my 3Box profile, it shows as updated on my activity list and visible on the left bar, but if I reload the page it is empty.
**To Reproduce**
1. Go to 'Edit Profile'
2. Update email
3. Click on 'Save'
4. Go to Profile page -> Email is visible
5. Reload Profile page -> Email is not visible
6. Edit Profile -> email is not visible

**Expected behavior**
Email should be there after reload

**Screenshots**
<img width="1074" alt="screen shot 2018-10-24 at 23 06 37" src="https://user-images.githubusercontent.com/5901730/47464767-349bb300-d7e2-11e8-9f40-f147cd0cc83b.png">

**Desktop (please complete the following information):**
MacOS and Chrome

**Comment by oznekenzo** [comment]
I will take a look @joaoaguiam, thanks for reporting

**Comment by oznekenzo** [comment]
@joaoaguiam the guys are working on getting this debugged
from @michaelsena 
"It basically has to do with the fact that users attempt to save their email before their DB is synced I believe" 
thanks again for reporting

**Comment by michaelsena** [comment]
Thanks @oznekenzo :+1:
