### ISSUE TITLE
Fine tune copy difference between Allow Consent & Allow Access (web3 breaking change update)

### ISSUE THREAD

**Issue by oznekenzo** [uport-project/3box-dapp#124]
There is a subtlety that needs to be made more clear between the difference in allowing access to the web3 object (eth address, wallet type etc) and allowing consent

**Comment by michaelsena** [comment]
@oznekenzo can you remind me where again in the app this appears? Can you please include a screenshot?

**Comment by oznekenzo** [comment]
@michaelsena sure - this happens when using MetaMask v5, after clicking Sign In / Create Profile and before asking for Consent

**Comment by oznekenzo** [comment]
<img width="555" alt="screen shot 2018-11-15 at 6 03 57 pm" src="https://user-images.githubusercontent.com/8059373/48587399-fedd7c00-e900-11e8-9432-c93a6b03d436.png">

**Comment by michaelsena** [comment]
Let's try:
**Approve 3Box in Web3 Wallet**
Make sure your web3 wallet is open and unlocked.

-- but separately, I dont think we need to say "Ethereum API Request" in the modal. It seems too technical for this image which will be seem by mainstream users too that dont know what an API is. What else can we put there?
@oznekenzo

**Comment by oznekenzo** [comment]
Cool, will update.  And will remove "Ethereum API Request".  That's what was being shown in the beta MetaMask released for developers to test the breaking change - I'll update it to what it displays now in v5 - "Connect Request"

**Comment by michaelsena** [comment]
We got some feedback on this @oznekenzo. Let's sync to update the copy.
