### ISSUE TITLE
http://www.alpha.3box.io/ results in error

### ISSUE THREAD

**Issue by oznekenzo** [uport-project/3box-dapp#129]

**Comment by c-castillo** [comment]
@oznekenzo 
That subdomain doesn't exists. It's not supposed to work that way

**Comment by oed** [comment]
@c-castillo Have you been able to experiment with another domain to learn what's the correct config to enable just https://3box.io ?

**Comment by c-castillo** [comment]
@oed I want to test it and leave it as https://3box.io
Let's discuss that in the standup.
