### ISSUE TITLE
Developer Research

### ISSUE THREAD

**Issue by oznekenzo** [uport-project/3box-dapp#135]
It would be nice to ask developers which fields they would like to return from getProfile, so we can think about prioritizing them in our dapp

**Comment by michaelsena** [comment]
Here is the first bit of research. Seems to indicate that our intuitions were more or less on target with verified contact info, linked social media accounts, and general Facebook About info. https://twitter.com/somemikesena/status/1062479255597211650

**Comment by michaelsena** [comment]
Here's some more research. Posting here before I close the story. 👍 
https://twitter.com/3boxdb/status/1064867887490449408
https://twitter.com/somemikesena/status/1064650205474242561
