### ISSUE TITLE
Add terms page to website

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box-dapp#36]

**Comment by oznekenzo** [comment]
Depends on if I am creating this page

**Comment by michaelsena** [comment]
This is 99% done @oznekenzo 
https://docs.google.com/document/d/1pdce2mB2yg81B68eePBEyxtCOdEQUUnHEFCzjT68hC0/edit?usp=sharing

**Comment by oznekenzo** [comment]
@michaelsena cool will start adding now
