### ISSUE TITLE
Update Landing Page

### ISSUE THREAD

**Issue by ozlemulusoy** [uport-project/3box-dapp#42]

**Comment by oznekenzo** [comment]
- [ ] add motion

**Comment by oznekenzo** [comment]
left align content on landing page
bigger header
more linespace on body of text on landing page
light blue for all buttons
anonymous user or illustration for landing page user
for all users as well
shorten ethereum address everywhere (user cards, profile, etc)
add modal for, you have to sign in to your metamask now (bloom)
change default picture to a low contrast grey (or think of ideas for another)
move email submission to top middle
make email submission not white
move social links to footer on landing page
terms and privacy below in middle
icon for each new address, use address to generate color (ten colors!)
