### ISSUE TITLE
Update Edit Profile Page

### ISSUE THREAD

**Issue by ozlemulusoy** [uport-project/3box-dapp#44]

**Comment by michaelsena** [comment]
@oznekenzo maybe you want to include your evernotes from our conversation yesterday on each page in the appropriate issues?

**Comment by oznekenzo** [comment]
@michaelsena Will do!

**Comment by oznekenzo** [comment]
unclear on photo edit - move
choose a file to "edit"
remove vs cancel
add image saved by save button on edit page form, remove edit photo modal
keep background same as landing page
have background have blue hue
add right column with that blue hue
experiment with border, non noticeable
take out footer from edit profile page
make edit profile page background the blue hue
remove line separating save
make whole form white
