### ISSUE TITLE
Have Conversation Regarding the Redux Actions, Reducers, Sagas Structure

### ISSUE THREAD

**Issue by KamesCG** [uport-project/3box-dapp#5]
I use a slightly different method for handling Redux actions and sagas that reduces the amount of reducers required to be written i.e. always expect a `payload` and `metadata` plus keep track of the status of the request in a single `reducer` that monitors all requests via `delta` identifier. That being said, the setup still allows for custom reducers if that need arises as demonstrated in the `ether.js` reducer.

This might cause some confusion for developers use to a more traditional Redux setup. Probably worth ripping out and using a more standard style.

```
export default (state = initialState, {type, payload, metadata, batch, entity} ) => {
  if(!!(metadata && metadata.delta) && entity === 'ethers') {
    return {
      ...state,
      [metadata.delta]: {
        ...state[metadata.delta],
        status: {
          REQUESTED: undefined,
          SUCCESS: true,
          FAILURE: false
        }[batch],
        data: payload
      }
    }
  } else{
    switch (type) {
      case actions.PROVIDER_CHANGE:
        return {
          ...state,
          provider: payload
        }
      case actions.CHAIN_CHANGE:
        return {
          ...state,
          chain: payload
        }
      case actions.JSONRPC_URL_CHANGE:
        return {
          ...state,
          url: payload
        }
      default:
        return state
    }
  }
}
```

**Comment by michaelsena** [comment]
closing
