### ISSUE TITLE
Create Client Install screen for mobile browser

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box-dapp#53]
As a user visiting 3Box.io from a mobile Safari/Chrome browser, I need to immediately see an interrupting screen that directs me to:
1. Button to install Coinbase Wallet
2. Button to Install Status.im

3. Directions to open site in Coinbase or Status Browser.

(see how 0x does it)

![Screen Shot 2018-10-01 at 10.01.40 PM.png](https://images.zenhubusercontent.com/5b1e6edb4b5806bc2bd704db/5fd5d68f-b6a4-46b7-8678-cb2a4bd9141d)

**Comment by michaelsena** [comment]
@oznekenzo adding another story related to mobile-compatibility and the Coinbase Wallet submission. Let me know if you have any questions.

**Comment by oznekenzo** [comment]
Sure thing!

**Comment by oznekenzo** [comment]
- [ ] if user is on conventional browser, prompt to use wallet or download

**Comment by oznekenzo** [comment]
Should we have matching download wallet prompt for desktop complete with download links?

**Comment by oznekenzo** [comment]
- [ ] switch status button to trust wallet or vault on iOS
