### ISSUE TITLE
Text Entry on Trust Wallet

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box-dapp#62]
**Describe the bug**
I use trust wallet, can't input lowerchase alphabet if not use copy paste text.

**To Reproduce**
1. Go to alpha.3box.io or sf.bounties.network on trustwallet mobile
2. Try to enter text
3. See uppercase

**Expected behavior**
Can type normally

**Tech**
 - Trust Wallet

**Comment by oed** [comment]
Sounds like a bug in Trust Wallet?

**Comment by ozlemulusoy** [comment]
Investigate.

**Comment by oznekenzo** [comment]
Works for me?

**Comment by oznekenzo** [comment]
Need to test with older samsung android devices.
unable to replicate bug
