### ISSUE TITLE
Unable to login with Status on Pixel 2

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box-dapp#63]
**Describe the bug**
Trying to complete SF Bounty, Create a Profile with 3Box, but Cannot create a Profile. Login screen just shows loading screen.

**To Reproduce**
1. Try to login with tech below.

**Expected behavior**
Logs me in.

**Tech**
Using Status App, with Android , Pixel 2

**Comment by oznekenzo** [comment]
I don't have this phone on hand to replicate - I can try downloading on my phone and/or @michaelsena we can cowork at some point this week to see it on your phone 🎉

**Comment by oznekenzo** [comment]
Added to existing story https://github.com/uport-project/3box-dapp/issues/105
