### ISSUE TITLE
Screen sizing weirdness on mobile landing page sometimes

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box-dapp#65]
**Describe the bug**
Landing page screen is all sized weirdly, too large right margin, some CSS styling thing.

**To Reproduce**
1. See screenshot

**Expected behavior**
Normal size

**Screenshots**
![screenshot_20181007-134842](https://user-images.githubusercontent.com/5216274/46639927-0ad26300-cb37-11e8-8b87-d4224c92ca26.png)

**Tech**
Using Status App, with Android , Pixel 2

**Additional context**
Reported during ETH SF Bug Bounty

**Comment by oznekenzo** [comment]
@michaelsena should be fixed with latest deployment!
