### ISSUE TITLE
Cannot login with Coinbase Wallet

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box-dapp#69]
**Describe the bug**
Try to log in by clicking "Create Profile" on landing page, see spinning wheel, ... it doesn't stop.

**To Reproduce**
1. Coinbase Wallet
2. alpha.3box.io
3. Click Create Profile
4. See spinning error

**Expected behavior**
I expect to promptly be logged in.

**Screenshots**
n/a

**Tech**
iOS, iPhone X, Coinbase Wallet

**Comment by oznekenzo** [comment]
Unable to reproduce

**Comment by michaelsena** [comment]
Seems to work now! Closing
