### ISSUE TITLE
Bug: The 3Box Profile Has React Error after Saving Nested Object via box.set method

### ISSUE THREAD

**Issue by KamesCG** [uport-project/3box-dapp#81]
**Describe the bug**
After saving a nested `object` using the `box.set`  method in my personal distributed application I'm unable to view my 3Box profile, because `Objects` are not valid React children.

**To Reproduce**
1. Save an `object` using `box.set` method

```
box.public.set('biography', {})
```

**Error Message:** https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=object%20with%20keys%20%7BbiographyTagline%2C%20biographyDescription%7D&args[]=

**Expected behavior**
View 3Box profile even if a developer sets a profile field with a nested object.

**Screenshots**
![Limbo](https://gateway.ipfs.io/ipfs/QmPgxczt5vosUhi3Jq25ZREUJuJy9RdSXZZsRcra86Xpkg)

**Comment by oznekenzo** [comment]
@KamesCG noted, thanks Kames!

**Comment by oznekenzo** [comment]
@KamesCG app should update in a few, let me know if the fix works for you!

**Comment by KamesCG** [comment]
Still receiving the error. I've done a complete application cache clear.

**Comment by oznekenzo** [comment]
An empty object? Ah, did not accommodate for that

**Comment by oznekenzo** [comment]
A nested object should work now though? Let me check

**Comment by oznekenzo** [comment]
@KamesCG Could you send me the shape of the object? Thx

**Comment by oznekenzo** [comment]
Hmmm, I hard coded that into the new code and it works.  That object is returned with the ```.value``` key correct?
