### ISSUE TITLE
Error: Unknown address - unable to sign message for this address: "null"

### ISSUE THREAD

**Issue by pedrouid** [uport-project/3box-dapp#82]
**Describe the bug**
Get Error for Unkwown address when creating a profile or signing in (happens both on Chrome and Brave)

**To Reproduce**
1. Go to https://alpha.3box.io/
2. Click on "Create Profile" or "Sign in"
3. Modal displays error stack (see screenshots)
3. Error also logged on console (see screenshots)

**Expected behavior**
Expected modal to prompt to create a new profile or signing in

**Screenshots**
<img width="1920" alt="screenshot 2018-10-15 12 23 53" src="https://user-images.githubusercontent.com/10136079/46973614-9b003300-d076-11e8-8de4-9415a4851e03.png">
<img width="1920" alt="screenshot 2018-10-15 12 24 33" src="https://user-images.githubusercontent.com/10136079/46973615-9b003300-d076-11e8-9c22-a88cab78bf95.png">
<img width="1285" alt="screenshot 2018-10-15 12 29 12" src="https://user-images.githubusercontent.com/10136079/46973616-9b98c980-d076-11e8-8645-894eee8d8f39.png">

**Desktop 1**
 - OS: MacOS High Sierra version 10.13.6 (17G65)
 - Browser: Brave version 0.25.2 (8ea2a9c)
 - Other: Metamask version 4.11.1

**Desktop 2**
 - OS: MacOS High Sierra version 10.13.6 (17G65)
 - Browser: Chrome version 69.0.3497.100 (64-bit)
 - Other: Metamask version 4.13.0

**Comment by pedrouid** [comment]
Ok after I refreshed I got it working now, so I'm guessing there was asynchronous event happening on first page load that missed the address but you can see on localstorage that it has both records
<img width="960" alt="screenshot 2018-10-15 12 38 26" src="https://user-images.githubusercontent.com/10136079/46973903-6a6cc900-d077-11e8-8994-f38092b055dd.png">

**Comment by oznekenzo** [comment]
Sorry for the radio silence - this one snuck past me - and thanks for writing the issue
I believe the recent updates should have handled this issue, comment if otherwise!
