### ISSUE TITLE
Sign up error

### ISSUE THREAD

**Issue by robertsolomon** [uport-project/3box-dapp#86]
**Describe the bug**
metamask signing UI is broken. cancelling brings up a weird error message.

**To Reproduce**
see video link

**Expected behavior**

**Screenshots**
https://soapbox.wistia.com/videos/UlRxKioU3O

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macos (mojave 10.14)
 - Browser [e.g. chrome, safari] chrome 69.0.3497.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by oznekenzo** [comment]
You have sign the consent request, do not hit cancel, on MetaMask

**Comment by robertsolomon** [comment]
If you watch in the video, the metamask signature UI is messed up. For all
I know, it could be having me send ether.

**Comment by oznekenzo** [comment]
We shouldn't have any influence on how MetaMask renders in your browser, perhaps something is going on in your browser/MetaMask?

**Comment by robertsolomon** [comment]
I'm sure it is, only making you aware as was requested in the uport slack
channel. I was just checking it out and I don't actually need to use the
application.
If a customer calls into Amazon saying they can't complete checkout, it's
probably the browser / credit processing provider Amazon contracted with
and not Amazon's web page, but Amazon still owns the bug.

**Comment by michaelsena** [comment]
Appreciate the report @robertsolomon! That does seem odd, have you ever experienced that with MM on Chrome before, or was this the first time it appeared distorted like that? :bug:

**Comment by rej156** [comment]
Seen that error pop up before when I wasn't on mainnet

**Comment by robertsolomon** [comment]
Yea definitely odd. I've never seen it render that way before no.

**Comment by oed** [comment]
This has been solved upstream and will probably be fixed in the next MM release.
